var namespaceel_1_1base =
[
    [ "debug", "namespaceel_1_1base_1_1debug.html", "namespaceel_1_1base_1_1debug" ],
    [ "threading", "namespaceel_1_1base_1_1threading.html", "namespaceel_1_1base_1_1threading" ],
    [ "utils", "namespaceel_1_1base_1_1utils.html", "namespaceel_1_1base_1_1utils" ],
    [ "DefaultLogBuilder", "classel_1_1base_1_1_default_log_builder.html", "classel_1_1base_1_1_default_log_builder" ],
    [ "DefaultLogDispatchCallback", "classel_1_1base_1_1_default_log_dispatch_callback.html", "classel_1_1base_1_1_default_log_dispatch_callback" ],
    [ "DefaultPerformanceTrackingCallback", "classel_1_1base_1_1_default_performance_tracking_callback.html", "classel_1_1base_1_1_default_performance_tracking_callback" ],
    [ "HitCounter", "classel_1_1base_1_1_hit_counter.html", "classel_1_1base_1_1_hit_counter" ],
    [ "LogDispatcher", "classel_1_1base_1_1_log_dispatcher.html", "classel_1_1base_1_1_log_dispatcher" ],
    [ "LogFormat", "classel_1_1base_1_1_log_format.html", "classel_1_1base_1_1_log_format" ],
    [ "MessageBuilder", "classel_1_1base_1_1_message_builder.html", "classel_1_1base_1_1_message_builder" ],
    [ "MillisecondsWidth", "classel_1_1base_1_1_milliseconds_width.html", "classel_1_1base_1_1_milliseconds_width" ],
    [ "NoCopy", "classel_1_1base_1_1_no_copy.html", "classel_1_1base_1_1_no_copy" ],
    [ "NullWriter", "classel_1_1base_1_1_null_writer.html", "classel_1_1base_1_1_null_writer" ],
    [ "PerformanceTracker", "classel_1_1base_1_1_performance_tracker.html", "classel_1_1base_1_1_performance_tracker" ],
    [ "PErrorWriter", "classel_1_1base_1_1_p_error_writer.html", "classel_1_1base_1_1_p_error_writer" ],
    [ "RegisteredHitCounters", "classel_1_1base_1_1_registered_hit_counters.html", "classel_1_1base_1_1_registered_hit_counters" ],
    [ "RegisteredLoggers", "classel_1_1base_1_1_registered_loggers.html", "classel_1_1base_1_1_registered_loggers" ],
    [ "StaticClass", "classel_1_1base_1_1_static_class.html", null ],
    [ "Storage", "classel_1_1base_1_1_storage.html", "classel_1_1base_1_1_storage" ],
    [ "TypedConfigurations", "classel_1_1base_1_1_typed_configurations.html", "classel_1_1base_1_1_typed_configurations" ],
    [ "VRegistry", "classel_1_1base_1_1_v_registry.html", "classel_1_1base_1_1_v_registry" ],
    [ "Writer", "classel_1_1base_1_1_writer.html", "classel_1_1base_1_1_writer" ]
];